version: '3.1'
services:

  app:
    build: ./
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
